apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: kcna-learn
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cGFzc3dvcmQ=  # password
  database: a2NuYV9sZWFybg==  # kcna_learn 